# -*- coding: UTF-8 -*-

IMA_SPECIE = 0

SUPERGROUP_SPECIE = 1.0
GROUP_SPECIE = 1.1
SUBGROUP_SPECIE = 1.2
ROOT_SPECIE = 1.3
SERIE_SPECIE = 1.4

CHEMICAL_SYNONYM = 2.0
COMMODITY_SYNONYM = 2.1
COMMON_SYNONYM = 2.2
OLD_SYNONYM = 2.3
RELATED_SYNONYM = 2.4
IDENTICAL_SYNONYM = 2.5
LANGUAGE_SYNONYM = 2.6
OBSOLETE_SYNONYM = 2.7
REGIONAL_SYNONYM = 2.8
SPELLING_SYNONYM = 2.9
STATUS_UNCERTAIN_SYNONYM = 2.11


STATUS_POLYTYPE = 3.0

CHEMICAL_VARIETY = 4.0
PHYSICAL_VARIETY = 4.1
COMPOSITION_VARIETY = 4.2
ORIGIN_VARIETY = 4.3
STRUCTURAL_VARIETY = 4.4
STATUS_UNCERTAIN_VARIETY = 4.05

ANTHROPOTYPE_MINERAL = 5.0
UNSTABLE_MINERAL = 5.1
SYNTHETIC_PHASE = 5.2
HYPOTHETICAL_MINERAL = 5.3

UNNAMED_MINERAL_BY_S_N = 6.0
UNNAMED_MINERAL = 6.1

ROCK_SPECIE = 7.0

MIXTURE_SPECIE = 8.0

OBSOLETE_MINERAL = 9.0
QUESTIONABLE_MINERAL = 9.1
NON_APPROVED_MINERAL = 9.2
SOLID_SOLUTION_MEMBER = 9.3

MINERALOID = 10.0
