version: "3.7"

services:

  certbot:
    image: certbot/dns-route53:v2.5.0
    platform: linux/amd64
    restart: 'no'
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_EMAIL: ${AWS_EMAIL}
      DOMAIN: ${DOMAIN}
    volumes:
      - ./nginx/certbot:/etc/letsencrypt
    command: ['certonly', '--dns-route53', '--agree-tos', '--no-eff-email', '--email', '${AWS_EMAIL}', '--cert-name', '${DOMAIN}', '-d', '${DOMAIN}']

  certbot-renew:
    image: certbot/dns-route53:v2.5.0
    platform: linux/amd64
    restart: 'no'
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_EMAIL: ${AWS_EMAIL}
      DOMAIN: ${DOMAIN}
    volumes:
      - .services/post-renew.sh:/post-renew.sh
      - ./nginx/certbot:/etc/letsencrypt
    command: ['renew', '--disable-hook-validation', '--deploy-hook', 'post-renew.sh']
