version: "3"
services:

    nginx-dev:
        container_name: nginx-dev
        restart: unless-stopped
        image: nginx:stable-alpine
        platform: linux/arm64
        ports:
            - "80:80"
        command: >
            /bin/sh -c "envsubst '$${DOMAIN}' < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"
        env_file:
            - ./.envs/.local/.nginx
        volumes:
            - ./nginx/dev/nginx.template:/etc/nginx/nginx.template:ro

            - ./nginx/_data/log:/var/log/nginx
            - ./nginx/_data/media:/var/www/media
            - ./nginx/_data/static:/var/www/static

    database:
        container_name: database
        build:
          context: .
          dockerfile: ./compose/local/db/Dockerfile
        restart: unless-stopped
        volumes:
            - ./db/services/dump_db.sh:/dump_db.sh:ro
            - ./db/services/restore_db.sh:/restore_db.sh:ro

            - database-data:/var/lib/postgresql/data/
            - ./db/backups:/backups
            - ./sql/:/sql
        env_file:
            - ./.envs/.local/.db
        ports:
            - "5432:5432"

    backend:
        container_name: backend
        build:
            context: .
            dockerfile: ./compose/local/backend/Dockerfile
        command: /start.sh
        restart: unless-stopped
        depends_on:
            - database
        env_file:
            - ./.envs/.local/.backend
            - ./.envs/.local/.db
            - ./.envs/.local/.nginx
        ports:
            - "8000:8000"
        volumes:
            - .:/app

            - ./nginx/_data/media:/app/media
            - ./nginx/_data/static:/app/static

volumes:
    database-data:
