version: "3.7"

services:

    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: ./compose/production/nginx/Dockerfile
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx/prod/:/etc/nginx/
            - ./nginx/_data/log:/var/log/nginx

            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
        env_file:
            - ./.envs/.prod/.nginx

    certbot:
        image: certbot/certbot
        restart: unless-stopped
        volumes:
            - ./nginx/certbot/conf:/etc/letsencrypt
            - ./nginx/certbot/www:/var/www/certbot
        entrypoint: >
            /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"

    backend:
        container_name: backend
        build:
            context: .
            dockerfile: ./compose/production/backend/Dockerfile
        restart: always
        image: registry.digitalocean.com/mr-project/backend:latest
        command: /start
        volumes:
            - .:/app
        ports:
            - 8000:8000
        env_file:
            - ./.envs/.prod/.backend
            - ./.envs/.prod/.db
            - ./.envs/.prod/.nginx
