version: "3.7"

services:

    nginx:
        container_name: nginx
        networks:
            - backend
        build:
            context: .
            dockerfile: ./compose/production/nginx/Dockerfile
        restart: always
        ports:
            - "80:80"
            - "443:443"
        expose:
            - "81"
        volumes:
            - ./nginx/prod/:/etc/nginx/
            - ./nginx/_data/log:/var/log/nginx
            - ./nginx/dhparam.pem:/etc/nginx/dhparam.pem:ro

            - /var/run/datadog/:/var/run/datadog/

            - ./nginx/certbot:/etc/letsencrypt:ro
        env_file:
            - ./.envs/.prod/.nginx

    backend:
        container_name: backend
        networks:
            - backend
        build:
            context: .
            dockerfile: ./compose/production/backend/Dockerfile
        restart: always
        image: registry.gitlab.com/mineralogy.rocks/mr-api/backend:latest
        command: /start
        volumes:
            - .:/app

            - /var/run/datadog/:/var/run/datadog/
        ports:
            - "8000:8000"
        env_file:
            - ./.envs/.prod/.backend
            - ./.envs/.prod/.db
            - ./.envs/.prod/.nginx
            - ./.envs/.prod/.do

    datadog:
        container_name: datadog
        build:
          context: .
          dockerfile: ./compose/production/datadog/Dockerfile
        pid: host
        networks:
            - backend
        links:
            - backend
            - nginx
        ports:
            - "8126:8126/tcp"
            - "8125:8125/udp"
        env_file:
            - ./.envs/.prod/.datadog
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /var/lib/docker/containers:/var/lib/docker/containers:ro
            - /proc/:/host/proc/:ro
            - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
            - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
            - /etc/os-release:/host/etc/os-release:ro
            - /opt/datadog/apm:/opt/datadog/apm
            - /var/run/datadog/:/var/run/datadog/

            - ./nginx/_data/log:/var/log/nginx


networks:
    backend:
        name: backend
        driver: bridge
