# Generated by Django 4.1.3 on 2023-10-16 19:20

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mineralcrystallography",
            name="mineral",
            field=models.OneToOneField(
                db_column="mineral_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crystallography",
                to="core.mineral",
            ),
        ),
    ]
