# Generated by Django 4.0.4 on 2022-04-29 09:45

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [TrigramExtension(), UnaccentExtension()]
