# Generated by Django 4.0.4 on 2022-06-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20220429_0945"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrystalClass",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("h_m_symbol", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Crystal Class",
                "verbose_name_plural": "Crystal Classes",
                "db_table": "crystal_class_list",
                "ordering": ["crystal_system", "name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CrystalSystem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Crystal System",
                "verbose_name_plural": "Crystal Systems",
                "db_table": "crystal_system_list",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="IonPosition",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Ion Position",
                "verbose_name_plural": "Ion Positions",
                "db_table": "ion_position_list",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MineralCrystallography",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("a", models.FloatField(blank=True, default=None, null=True)),
                ("b", models.FloatField(blank=True, default=None, null=True)),
                ("c", models.FloatField(blank=True, default=None, null=True)),
                ("alpha", models.FloatField(blank=True, default=None, null=True)),
                ("gamma", models.FloatField(blank=True, default=None, null=True)),
                ("z", models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                "verbose_name": "Crystallography",
                "verbose_name_plural": "Crystallographies",
                "db_table": "mineral_crystallography",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SpaceGroup",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "verbose_name": "Space Group",
                "verbose_name_plural": "Space Groups",
                "db_table": "space_group_list",
                "ordering": ["name"],
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Nationality",
        ),
    ]
