# Generated by Django 4.1.3 on 2023-10-16 19:26

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_mineralcrystallography_mineral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crystalclass",
            name="crystal_system",
            field=models.ForeignKey(
                db_column="crystal_system_id",
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="core.crystalsystem",
            ),
        ),
    ]
