# Generated by Django 3.1.2 on 2020-11-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200930_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsSpeciesCountry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField(db_column='note', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ms_species_countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MsSpeciesRelation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relation_note', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ms_species_relations',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MsSpeciesCountries',
        ),
        migrations.DeleteModel(
            name='MsSpeciesRelations',
        ),
    ]
