# Generated by Django 4.1.3 on 2023-10-16 20:04

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_crystalclass_crystal_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crystalsystem",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="mineralcrystallography",
            name="crystal_system",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "hexagonal"),
                    (2, "isometric"),
                    (3, "monoclinic"),
                    (4, "orthorhombic"),
                    (5, "tetragonal"),
                    (6, "triclinic"),
                    (7, "trigonal"),
                    (8, "amorphous"),
                    (9, "icosahedral"),
                ],
                default=None,
                null=True,
            ),
        ),
    ]
