# Generated by Django 4.0.4 on 2022-08-01 08:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_crystalclass_crystalsystem_ionposition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MineralIonPosition",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "quantity",
                    models.TextField(blank=True, db_column="ion_quantity", null=True),
                ),
            ],
            options={
                "verbose_name": "Mineral Ions",
                "verbose_name_plural": "Minerals Ions",
                "db_table": "mineral_ion_position",
                "ordering": ["mineral"],
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="ionposition",
            options={
                "managed": False,
                "ordering": ["name"],
                "verbose_name": "Ion Position",
                "verbose_name_plural": "Ion Positions",
            },
        ),
    ]
