# Generated by Django 3.1.2 on 2020-11-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201106_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoClass',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.TextField()),
            ],
            options={
                'db_table': 'ions_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IoGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.TextField()),
            ],
            options={
                'db_table': 'ions_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IonsList',
            fields=[
                ('ion_id', models.AutoField(primary_key=True, serialize=False)),
                ('ion_name', models.TextField()),
                ('formula', models.CharField(max_length=100)),
                ('formula_with_oxidation', models.CharField(max_length=100, null=True)),
                ('expressed_as', models.TextField(null=True)),
                ('structure_description', models.TextField(null=True)),
                ('geometry', models.TextField(null=True)),
            ],
            options={
                'db_table': 'ions_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IonsTypesList',
            fields=[
                ('ion_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('ion_type_name', models.TextField()),
            ],
            options={
                'db_table': 'ions_types_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IoSubclass',
            fields=[
                ('subclass_id', models.AutoField(primary_key=True, serialize=False)),
                ('subclass_name', models.TextField()),
            ],
            options={
                'db_table': 'ions_subclass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IoSubgroup',
            fields=[
                ('subgroup_id', models.AutoField(primary_key=True, serialize=False)),
                ('subgroup_name', models.TextField()),
            ],
            options={
                'db_table': 'ions_subgroup',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='msspeciescountry',
            table='ms_species_country',
        ),
        migrations.AlterModelTable(
            name='msspeciesrelation',
            table='ms_species_relation',
        ),
    ]
