# Generated by Django 4.1.1 on 2022-09-16 13:59

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_mineralionposition_alter_ionposition_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormulaSource",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "Formula Source",
                "verbose_name_plural": "Formula Sources",
                "db_table": "formula_source_list",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MineralFormula",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "formula",
                    models.CharField(
                        blank=True,
                        help_text="Mineral formula in different formats.",
                        max_length=1000,
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "show_on_site",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a specific formula has a priority over the others and thefore should be shown on site.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formula",
                "verbose_name_plural": "Formulas",
                "db_table": "mineral_formula",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="MineralRelationSuggestion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "relation_type",
                    models.IntegerField(
                        db_column="relation_type_id",
                        help_text="Relation type according to mindat.",
                        null=True,
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, help_text="Is the suggestion processed?"
                    ),
                ),
            ],
            options={
                "verbose_name": "Relation Suggestion",
                "verbose_name_plural": "Relation Syggestions",
                "db_table": "mineral_relation_suggestion",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="mineralhistory",
            options={
                "managed": False,
                "verbose_name": "Discovery Context",
                "verbose_name_plural": "Discovery contexts",
            },
        ),
    ]
