# Generated by Django 4.1.3 on 2023-11-03 18:03

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_mineralcrystallography_crystal_system"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mineral",
            name="ima_notes",
        ),
        migrations.RemoveField(
            model_name="mineral",
            name="ima_statuses",
        ),
        migrations.AlterField(
            model_name="mineralimanote",
            name="mineral",
            field=models.ForeignKey(
                db_column="mineral_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ima_notes",
                to="core.mineral",
            ),
        ),
        migrations.AlterField(
            model_name="mineralimanote",
            name="note",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Rejected"),
                    (2, "Pending Approval"),
                    (3, "Group"),
                    (4, "Redefined"),
                    (5, "Renamed"),
                    (6, "Intermediate"),
                    (7, "Published without Approval"),
                    (8, "Unnamed Valid"),
                    (9, "Unnamed Invalid"),
                    (10, "Named Amphibole"),
                ],
                db_column="ima_note_id",
                default=None,
            ),
        ),
        migrations.AlterField(
            model_name="mineralimastatus",
            name="mineral",
            field=models.ForeignKey(
                db_column="mineral_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ima_statuses",
                to="core.mineral",
            ),
        ),
        migrations.AlterField(
            model_name="mineralimastatus",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Approved"),
                    (2, "Discredited"),
                    (3, "Pending Publication"),
                    (4, "Grandfathered"),
                    (5, "Questionable"),
                ],
                db_column="ima_status_id",
                default=None,
            ),
        ),
        migrations.DeleteModel(
            name="IMANote",
        ),
        migrations.DeleteModel(
            name="IMAStatus",
        ),
    ]
