# Generated by Django 4.1.3 on 2023-11-07 19:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_remove_mineral_ima_notes_remove_mineral_ima_statuses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mineralcrystallography",
            name="is_inherited",
            field=models.BooleanField(default=False, help_text="Is the data inherited from parent?"),
        ),
    ]
