# Generated by Django 4.1.3 on 2023-12-11 14:08

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_mineralcrystallography_is_inherited"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mineralcrystallography",
            name="is_inherited",
        ),
        migrations.AddField(
            model_name="mineralcrystallography",
            name="inherited_from",
            field=models.ForeignKey(
                default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.mineral"
            ),
        ),
    ]
