# Generated by Django 4.1.3 on 2023-12-11 17:43

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_mineralcrystallography_is_inherited_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mineralcrystallography",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
