# Generated by Django 4.1.3 on 2023-12-14 10:02

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_mineralcrystallography_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mineralcrystallography",
            name="inherited_from",
        ),
        migrations.CreateModel(
            name="MineralInheritance",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prop",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Inherit Formula"), (2, "Inherit Crystal System")], db_column="prop_id"
                    ),
                ),
                (
                    "inherit_from",
                    models.ForeignKey(
                        db_column="inherit_from_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descendants",
                        to="core.mineral",
                    ),
                ),
                (
                    "mineral",
                    models.ForeignKey(
                        db_column="mineral_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inheritance_chain",
                        to="core.mineral",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inheritance",
                "verbose_name_plural": "Inheritances",
                "db_table": "mineral_inheritance",
            },
        ),
    ]
