# Generated by Django 3.1.2 on 2021-01-29 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201229_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineralHierarchy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_top_level', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'MineralHierarchy',
                'db_table': 'mineral_hierarchy',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='grhierarchy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grhierarchy',
            name='mineral_id',
            field=models.ForeignKey(db_column='mineral_id', on_delete=django.db.models.deletion.CASCADE, related_name='mineral_test', to='api.minerallist'),
        ),
    ]
