# Generated by Django 3.1.2 on 2021-05-01 14:52

from django.db import migrations
from migrate_run_sql import *

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210129_1806'),
    ]

    operations = [
        migrations.RunPython(run_sql_file('adjust_db.sql')),
    ]
