# Generated by Django 4.1.3 on 2024-02-03 13:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_remove_mineralinheritance_updated_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mineralinheritance",
            index=models.Index(fields=["mineral"], name="mineral_inh_mineral_759164_idx"),
        ),
        migrations.AddIndex(
            model_name="mineralinheritance",
            index=models.Index(fields=["prop"], name="mineral_inh_prop_id_c22b36_idx"),
        ),
        migrations.AddIndex(
            model_name="mineralinheritance",
            index=models.Index(fields=["inherit_from"], name="mineral_inh_inherit_be4b39_idx"),
        ),
    ]
