# Generated by Django 3.1.2 on 2021-05-01 18:29

from django.db import migrations, models
from migrate_run_sql import *

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_adjust_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuxtTabs',
            fields=[
                ('tab_id', models.AutoField(primary_key=True, serialize=False)),
                ('tab_short_name', models.CharField(max_length=50, unique=True)),
                ('tab_long_name', models.TextField()),
            ],
            options={
                'db_table': 'nuxt_tabs',
                'managed': False,
            },
        ),
        migrations.RunPython(run_sql_file('adjust_db.sql')),
    ]
