# Generated by Django 5.0.2 on 2024-07-02 13:09

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_mineralinheritance_mineral_inh_mineral_759164_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mineralrelation",
            name="mineral",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="direct_relations", to="core.mineral"
            ),
        ),
        migrations.AddIndex(
            model_name="mineralcontext",
            index=models.Index(fields=["mineral"], name="mineral_con_mineral_16d67b_idx"),
        ),
    ]
