# Generated by Django 3.1.2 on 2020-11-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201111_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grhierarchy',
            old_name='group',
            new_name='group_id',
        ),
        migrations.RenameField(
            model_name='grhierarchy',
            old_name='mineral',
            new_name='mineral_id',
        ),
        migrations.RenameField(
            model_name='grhierarchy',
            old_name='root',
            new_name='root_id',
        ),
        migrations.RenameField(
            model_name='grhierarchy',
            old_name='serie',
            new_name='serie_id',
        ),
        migrations.RenameField(
            model_name='grhierarchy',
            old_name='subgroup',
            new_name='subgroup_id',
        ),
        migrations.RenameField(
            model_name='grhierarchy',
            old_name='supergroup',
            new_name='supergroup_id',
        ),
    ]
