# Generated by Django 3.1.2 on 2020-11-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201119_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsNamesPerson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('person', models.CharField(max_length=200)),
                ('born', models.IntegerField(null=True)),
                ('died', models.IntegerField(null=True)),
                ('role', models.TextField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'db_table': 'ms_names_person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NationalitiesList',
            fields=[
                ('nationality_id', models.AutoField(primary_key=True, serialize=False)),
                ('nationality_name', models.CharField(max_length=200)),
                ('note', models.TextField(null=True)),
            ],
            options={
                'db_table': 'nationalities_list',
                'managed': False,
            },
        ),
    ]
