# Generated by Django 3.1.2 on 2020-11-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_msnamesperson_nationalitieslist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagesList',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=200, unique=True)),
                ('language_group', models.CharField(max_length=200, null=True)),
                ('other_names', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('scope', models.CharField(max_length=200, null=True)),
                ('standard_639_1', models.CharField(max_length=100, null=True)),
                ('standard_639_2', models.CharField(max_length=100, null=True)),
                ('standard_639_3', models.CharField(max_length=100, null=True)),
                ('standard_639_5', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'languages_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MsNamesLanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meaning', models.TextField(null=True)),
                ('stem_1', models.TextField(null=True)),
                ('stem_2', models.TextField(null=True)),
                ('stem_3', models.TextField(null=True)),
            ],
            options={
                'db_table': 'ms_names_language',
                'managed': False,
            },
        ),
    ]
