# Generated by Django 3.1.2 on 2020-12-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201228_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineralNameInstitution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.TextField()),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'MineralNameInstitution',
                'db_table': 'mineral_name_institution',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='mineralnamelanguage',
            options={'managed': False, 'verbose_name_plural': 'MineralNameLanguage'},
        ),
        migrations.AlterModelTable(
            name='ionsubgrouplist',
            table='ion_subgroup_list',
        ),
    ]
