# Generated by Django 3.1.2 on 2020-11-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201111_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTypesList',
            fields=[
                ('ion_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('ion_type_name', models.TextField()),
            ],
            options={
                'db_table': 'io_types_list',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='IonsTypesList',
        ),
    ]
