FROM nginx:1.17.10-alpine

# ARG DOMAIN
# ENV DOMAIN=${DOMAIN}
# RUN echo "${DOMAIN}"

# COPY ./nginx/prod/ ./etc/nginx/

# RUN chown -R nginx:nginx /etc/nginx

# CMD /bin/sh -c "envsubst '$$DOMAIN' < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf.tmp && mv /etc/nginx/nginx.conf.tmp /etc/nginx/nginx.conf && while :; do sleep 6h & wait $!; nginx -s reload; done & nginx -g 'daemon off;'"
