#!/bin/sh

export DOMAIN

envsubst '${DOMAIN}' < /etc/nginx/conf.d/templates/domain.conf > /etc/nginx/conf.d/domain.conf && \
envsubst '${DOMAIN}' < /etc/nginx/conf.d/templates/no-ssl.domain.conf > /etc/nginx/conf.d/no-ssl.domain.conf && \
envsubst '${DOMAIN}' < /etc/nginx/h5bp/tls/templates/certificate_files.conf > /etc/nginx/h5bp/tls/certificate_files.conf && \
envsubst '${DOMAIN}' < /etc/nginx/h5bp/cross-origin/templates/requests.conf > /etc/nginx/h5bp/cross-origin/requests.conf

exec "$@"
