# Generated by Django 5.0.2 on 2024-05-08 07:26

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    replaces = [
        ("blog", "0001_initial"),
        ("blog", "0002_alter_category_options_alter_post_options_and_more"),
        ("blog", "0003_alter_post_options_category_slug"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=200, null=True, unique=True)),
            ],
            options={
                "ordering": ["id"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "ordering": ["id"],
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("likes", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="blog.category",
                    ),
                ),
                ("tags", models.ManyToManyField(related_name="posts", to="blog.tag")),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                "ordering": ["-published_at"],
                "verbose_name": "Post",
                "verbose_name_plural": "Posts",
            },
        ),
    ]
