apiVersion: batch/v1
kind: CronJob
metadata:
  name: sync-mindat
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mr-api
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command: ['python', '../../../src/app/manage.py', 'check']
            # command:
            # - /bin/sh
            # - -c
            # - date; echo Hello from the Kubernetes cluster
          restartPolicy: Never
